version: '3'

services:
  nacos:
    image: nacos:vcarl
    environment:
      - "PREFER_HOST_MODE=hostname"
      - "MODE=standalone"
      - "SPRING_DATASOURCE_PLATFORM=mysql"
      - "MYSQL_SERVICE_HOST=mysql"
      - "MYSQL_SERVICE_PORT=3306"
      - "MYSQL_SERVICE_DB_NAME=febs_nacos"
      - "MYSQL_SERVICE_USER=root"
      - "MYSQL_SERVICE_PASSWORD=123456"
    volumes:
      - ./dint/nacos/standalone-logs/:/home/nacos/logs
      - ./dint-init/nacos/application.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8001:8001
    networks:
      - default
    restart: on-failure
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    networks:
      - default
    volumes:
      - ./dint/mysql/data:/var/lib/mysql #挂载 MySQL数据
  redis:
    image: redis:4.0.14
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    volumes:
      - ./dint/redis/data:/data #挂载 Redis数据
      - ./dint/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf #挂载 Redis配置
    ports:
      - 6379:6379
    networks:
      - default
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - '20000:80'
      - '20443:443'
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - default
networks:
  default:
    external:
      name: overlay-dint

volumes:
  mariadb_data:
    driver: local
  phpmyadmin_data:
    driver: local
